language: android
android:
  components:
    - tools
    - android-30
    - build-tools-30.0.3
    - extra-android-m2repository
    - extra-android-support

  licenses:
    - android-sdk-license-.+

jdk:
  - oraclejdk8
