language: android
android:
  components:
    - tools
    - android-26
    - build-tools-26.0.1
    - extra-android-m2repository
    - extra-android-support

  licenses:
    - android-sdk-license-.+

jdk:
  - oraclejdk8
