language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
     - platform-tools
     - tools

before_install:
    android update sdk --filter extra-android-support --no-ui --force > /dev/null
    android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null
