language: android
android:
  components:
    - tools
    - android-27
    - build-tools-27.0.3
    - extra-android-m2repository
    - extra-android-support

  licenses:
    - android-sdk-license-.+

jdk:
  - oraclejdk8
