language: android
android:
  components:
    - tools
    - android-29
    - build-tools-29.0.2
    - extra-android-m2repository
    - extra-android-support

  licenses:
    - android-sdk-license-.+

jdk:
  - oraclejdk8
